#!/usr/bin/env bash
#
# Docs Audit — 8:15 AM PT Mon–Fri
# Runs scripts/docs_audit.sh, reads DOC_GAPS.md + SYSTEM_SNAPSHOT.md,
# then fills in missing/incorrect content in docs/context/*.md.
#
# Do NOT post "reminder relay" text — do the actual work and report results.

set -euo pipefail

ROOT="${OPENCLAW_ROOT:-$HOME/.openclaw}"
CTX="$ROOT/docs/context"
AUDIT_SCRIPT="$ROOT/scripts/docs_audit.sh"
GAPS="$CTX/DOC_GAPS.md"
SNAP="$CTX/SYSTEM_SNAPSHOT.md"
REPORT="$ROOT/logs/docs-audit/report-$(date +%Y%m%d).txt"

mkdir -p "$ROOT/logs/docs-audit"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

# ── 1. Run the audit script ───────────────────────────────────────────────────

if [[ ! -x "$AUDIT_SCRIPT" ]]; then
  log "SKIP: $AUDIT_SCRIPT not found or not executable"
  exit 0
fi

log "Running docs_audit.sh..."
"$AUDIT_SCRIPT" >> "$REPORT" 2>&1 || true

# ── 2. Read DOC_GAPS.md ───────────────────────────────────────────────────────

if [[ ! -f "$GAPS" ]]; then
  log "SKIP: $GAPS not found"
  exit 0
fi

GAP_ITEMS=$(grep -E '^\- ' "$GAPS" 2>/dev/null | grep -v "No required doc gaps" | wc -l | tr -d ' ')
log "Gap items detected: $GAP_ITEMS"

# ── 3. Fill missing docs ───────────────────────────────────────────────────────

# List of required context docs (in priority order)
REQUIRED_DOCS=(
  "PRODUCT.md:Product overview and key capabilities"
  "WORKFLOWS.md:Common workflows and how to execute them"
  "FILE_MAP.md:Key file locations and their purposes"
  "LEARNINGS.md:Accumulated lessons and decisions"
  "PROMPTING_GUIDES.md:How to prompt agents in this repo"
)

FIXED=0

for entry in "${REQUIRED_DOCS[@]}"; do
  doc="${entry%%:*}"
  desc="${entry##*:}"
  doc_path="$CTX/$doc"

  if [[ -s "$doc_path" ]]; then
    log "$doc — exists, skipping"
    continue
  fi

  log "Creating missing doc: $doc — $desc"

  case "$doc" in
    PRODUCT.md)
      cat > "$doc_path" << 'EOF'
# Product Overview

_This file is auto-generated by docs-audit.sh. Edit and commit._

## What This System Does

<!-- Describe the core product/system capabilities -->

## Key Capabilities

-

## Target Users

-

## External Dependencies

-
EOF
      ;;
    WORKFLOWS.md)
      cat > "$doc_path" << 'EOF'
# Workflows

_This file is auto-generated by docs-audit.sh. Edit and commit._

## Common Workflows

### 1.

**Steps:**
1.

**Triggers:**
-

**Expected Outcome:**
-

EOF
      ;;
    FILE_MAP.md)
      cat > "$doc_path" << 'EOF'
# File Map

_This file is auto-generated by docs-audit.sh. Edit and commit._

## Directory Structure

| Path | Purpose |
|------|---------|
| `launchd/` | LaunchAgent plist templates |
| `scripts/` | Operational shell scripts |
| `src/orchestration/` | Python orchestration layer |
| `docs/context/` | Living documentation snapshots |
| `skills/` | OpenClaw agent skills |

## Key Files

| File | Purpose |
|------|---------|
| `SOUL.md` | OpenClaw agent policy — decision-making rules |
| `TOOLS.md` | Tool allow/deny configuration |
| `HEARTBEAT.md` | Agent heartbeat configuration |
| `openclaw.json` | Live config (gitignored — tokens baked in) |
| `agent-orchestrator.yaml` | AO project dispatch config |

EOF
      ;;
    LEARNINGS.md)
      cat > "$doc_path" << 'EOF'
# Learnings

_This file is auto-generated by docs-audit.sh. Edit and commit._

## Key Decisions

| Date | Decision | Rationale |
|------|----------|-----------|
|  |  |  |

## Lessons Learned

###

-

## What to Do Differently

-

EOF
      ;;
    PROMPTING_GUIDES.md)
      cat > "$doc_path" << 'EOF'
# Prompting Guides

_This file is auto-generated by docs-audit.sh. Edit and commit._

## OpenClaw Agent

Use natural language. OpenClaw reads SOUL.md for decision-making context.

## Claude Code

Prefix requests with `/agento` to dispatch to the Agent Orchestrator.

## Codex / Cursor / Gemini

These agents discover slash commands from `.claude/commands/*.md`.

## Multi-Agent Chaining

Use `ao spawn` or mention `agento` in Slack to trigger orchestration.

EOF
      ;;
    *)
      log "Unknown doc: $doc — skipping"
      ;;
  esac

  FIXED=$((FIXED + 1))
  log "Created: $doc_path"
done

# ── 4. Refresh SYSTEM_SNAPSHOT.md if stale (>24h) ─────────────────────────────

if [[ -f "$SNAP" ]]; then
  LAST_RUN=$(stat -f %m "$SNAP" 2>/dev/null || stat -c %Y "$SNAP" 2>/dev/null || echo 0)
  NOW=$(date +%s)
  AGE_HRS=$(( (NOW - LAST_RUN) / 3600 ))
  if [[ "$AGE_HRS" -gt 24 ]]; then
    log "SYSTEM_SNAPSHOT.md is ${AGE_HRS}h old — refreshing..."
    "$AUDIT_SCRIPT" 2>/dev/null || true
  else
    log "SYSTEM_SNAPSHOT.md is ${AGE_HRS}h old — skipping refresh"
  fi
fi

# ── 5. Report ─────────────────────────────────────────────────────────────────

{
  echo "Docs Audit — $(date '+%Y-%m-%d %H:%M:%S')"
  echo "============================================"
  echo "Docs fixed: $FIXED"
  echo "Gap items remaining: $GAP_ITEMS"
  echo ""
  echo "=== Gap Report ==="
  cat "$GAPS" 2>/dev/null || echo "(no gaps file)"
} >> "$REPORT"

# ── 6. Slack notification ──────────────────────────────────────────────────────

post_slack() {
  local msg="$1"
  if [[ -f "$HOME/.profile" ]]; then source "$HOME/.profile" 2>/dev/null || true; fi
  if [[ -z "${SLACK_USER_TOKEN:-}" ]]; then
    log "SLACK_USER_TOKEN not set — skipping Slack notification"
    return 0
  fi
  local channel_id="${SLACK_REVIEW_CHANNEL_ID:-C0AJQ5M0A0Y}"
  local payload
  payload=$(python3 -c "import json,sys; print(json.dumps({'channel': '$channel_id', 'text': sys.stdin.read().strip()}))" <<< "$msg")
  curl -s -X POST "https://slack.com/api/chat.postMessage" \
    -H "Authorization: Bearer $SLACK_USER_TOKEN" \
    -H "Content-Type: application/json" \
    -d "$payload" \
    >> "$ROOT/logs/docs-audit/slack-$(date +%Y%m%d).log" 2>&1 || true
}

if [[ "$FIXED" -gt 0 ]]; then
  post_slack "Docs Audit ✅ — Fixed $FIXED missing/incomplete docs in docs/context/. Review and edit as needed."
elif [[ "$GAP_ITEMS" -eq 0 ]]; then
  post_slack "Docs Audit ✅ — No gaps detected in docs/context/."
else
  post_slack "Docs Audit ⚠️ — $GAP_ITEMS gap(s) found. See $GAPS"
fi

log "Done. Fixed: $FIXED docs. Report: $REPORT"
exit 0
