#!/usr/bin/env bash
# lean-memory-context.sh — Generate stripped-down memory context for quick tasks
# Reduces memory context from 148KB (86 projects) to ~15KB (current project, last 7 days)
set -euo pipefail

LEAN_OUTPUT="$HOME/.smartclaw/workspace/claude-memory-context-lean.md"
PROJECTS_DIR="$HOME/.claude/projects"
DAYS_BACK=7

# Detect current project from CWD
# CWD might be a worktree: ${HOME}/projects/agent-orchestrator
# or directly in ~/.claude/projects/...
detect_project() {
    local cwd="$1"
    local project_name=""

    # Handle ~/.smartclaw path (this repo IS openclaw)
    if [[ "$cwd" == *"/.smartclaw"* ]] || [[ "$cwd" == *"/openclaw" ]]; then
        echo "-Users-jleechan--openclaw"
        return
    fi

    # Try to match CWD against known project paths
    # Handle worktree paths: ~/projects/<project_name> or ~/worktree-<project_name>
    if [[ "$cwd" =~ /projects/([^/]+) ]]; then
        project_name="${BASH_REMATCH[1]}"
    elif [[ "$cwd" =~ /worktrees?/([^/]+) ]]; then
        project_name="${BASH_REMATCH[1]}"
    elif [[ "$cwd" =~ /worktree-([^/]+) ]]; then
        project_name="${BASH_REMATCH[1]}"
    fi

    # Map common project aliases to Claude projects dir names
    case "$project_name" in
        agent-orchestrator) echo "-Users-jleechan-project-agento-agent-orchestrator" ;;
        worldarchitect-ai|worldarchitect) echo "-Users-jleechan-projects-worldarchitect-ai" ;;
        ai-universe-living-blog|ai-universe|living-blog) echo "-Users-jleechan-projects-other-ai-universe-living-blog" ;;
        worldai-claw|worldaiclaw) echo "-Users-jleechan-project-worldaiclaw-worldai-claw" ;;
        worldclaw-dev|worldclaw_dev) echo "-Users-jleechan-worktree-worldclaw-dev" ;;
        smartclaw|jc-claw) echo "-Users-jleechan-project-smartclaw-smartclaw" ;;
        user-scope|user_scope) echo "-Users-jleechan-projects-other-user-scope" ;;
        harness|harness-automation) echo "-Users-jleechan-projects-worktree-harness" ;;
        genesis|worktree-genesis) echo "-Users-jleechan-projects-worktree-genesis" ;;
        openclaw) echo "-Users-jleechan--openclaw" ;;
        *) echo "$project_name" ;;
    esac
}

# Get cutoff date (7 days ago)
get_cutoff_date() {
    date -j -v-${DAYS_BACK}d '+%Y-%m-%d' 2>/dev/null || \
    date -d "-${DAYS_BACK} days" '+%Y-%m-%d'
}

# Main
CWD="$(pwd)"
TIMESTAMP=$(date '+%Y-%m-%dT%H:%M:%S%z')
CUTOFF_DATE=$(get_cutoff_date)

PROJECT_DIR_NAME=$(detect_project "$CWD")
MEMORY_FILE="$PROJECTS_DIR/$PROJECT_DIR_NAME/memory/MEMORY.md"

echo "# Lean Memory Context — $TIMESTAMP" > "$LEAN_OUTPUT"
echo "" >> "$LEAN_OUTPUT"
echo "Project: $PROJECT_DIR_NAME (CWD: $CWD)" >> "$LEAN_OUTPUT"
echo "Cutoff: $CUTOFF_DATE (last $DAYS_BACK days)" >> "$LEAN_OUTPUT"
echo "" >> "$LEAN_OUTPUT"
echo "Generated by lean-memory-context.sh. Do not edit manually." >> "$LEAN_OUTPUT"
echo "" >> "$LEAN_OUTPUT"

if [[ -r "$MEMORY_FILE" ]]; then
    echo "## [$PROJECT_DIR_NAME]" >> "$LEAN_OUTPUT"
    echo "" >> "$LEAN_OUTPUT"
    
    # Filter to last 7 days + cap at 20KB
    {
        grep -v '^# Memory Index$' "$MEMORY_FILE" | grep -v "^$" || true
    } | {
        # Take first 20KB of content after filtering
        head -c 20000
    } >> "$LEAN_OUTPUT"
    
    echo "" >> "$LEAN_OUTPUT"
    echo "*Lean context generated at $TIMESTAMP*" >> "$LEAN_OUTPUT"
    echo "claude-memory: lean context -> $LEAN_OUTPUT ($(wc -c < "$LEAN_OUTPUT") bytes)"
else
    echo "claude-memory: no memory file found for project: $PROJECT_DIR_NAME"
    echo "# No project memory found" >> "$LEAN_OUTPUT"
    echo "Project: $PROJECT_DIR_NAME" >> "$LEAN_OUTPUT"
    echo "Memory file not found: $MEMORY_FILE" >> "$LEAN_OUTPUT"
fi

# Atomic rename not needed for output file (not replacing the main context)
echo "claude-memory: lean context written to $LEAN_OUTPUT ($(wc -c < "$LEAN_OUTPUT") bytes)"
