#!/usr/bin/env bash
# sync-openclaw-config.sh — Sync openclaw.json.redacted from live config
#
# This script:
#   1. Copies live openclaw.json to a temp location (never into the worktree)
#   2. Regenerates openclaw.json.redacted using generate_redacted_config.py
#   3. Commits changes if there are any (idempotent — no-op if no changes)
#
# Usage: ./scripts/sync-openclaw-config.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LIVE_CONFIG="$HOME/.smartclaw/openclaw.json"
REDACTED_CONFIG="$REPO_ROOT/openclaw.json.redacted"

# Check prerequisites
if [[ ! -f "$LIVE_CONFIG" ]]; then
  echo "ERROR: Live config not found at $LIVE_CONFIG"
  exit 1
fi

if [[ ! -f "$REPO_ROOT/scripts/generate_redacted_config.py" ]]; then
  echo "ERROR: generate_redacted_config.py not found at $REPO_ROOT/scripts/"
  exit 1
fi

# Check if we're in a git repo (supports both regular repos and worktrees)
if [[ ! -d "$REPO_ROOT/.git" ]] && ! git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  echo "ERROR: Not a git repo: $REPO_ROOT"
  exit 1
fi

cd "$REPO_ROOT"

# Generate redacted config from a temp copy outside the repo worktree
TEMP_CONFIG=$(mktemp)
trap 'rm -f "$TEMP_CONFIG"' EXIT
cp "$LIVE_CONFIG" "$TEMP_CONFIG"

# Track changes before regeneration
BEFORE_REDACTED=$(cat "$REDACTED_CONFIG" 2>/dev/null || echo "")

# Regenerate redacted config
echo "Regenerating redacted config..."
python3 "$REPO_ROOT/scripts/generate_redacted_config.py" "$TEMP_CONFIG" "$REDACTED_CONFIG"

# Check if there are changes to commit
AFTER_REDACTED=$(cat "$REDACTED_CONFIG")
if [[ "$BEFORE_REDACTED" != "$AFTER_REDACTED" ]]; then
  echo ""
  echo "Changes detected — committing..."
  git add "$REDACTED_CONFIG"
  if git diff --cached --quiet; then
    echo "  (no changes to commit or already up-to-date)"
  else
    git commit --only -- "$REDACTED_CONFIG" -m "chore: sync openclaw.json.redacted from live config

Generated by sync-openclaw-config.sh"
    echo "✓ Config synced and committed"
  fi
else
  echo "✓ Config already up-to-date (no changes)"
fi
