#!/usr/bin/env bash
# sync-claude-memory.sh — Aggregate Claude Code memory files into OpenClaw context
set -euo pipefail

MEMORY_INDEX="$HOME/.openclaw/workspace/claude-memory-context.md"
CLAUDE_PROJECTS_DIR="$HOME/.claude/projects"
TIMESTAMP=$(date '+%Y-%m-%dT%H:%M:%S%z')

# Write to a temp file then atomically rename — consumers never see partial writes
TEMP_FILE="${MEMORY_INDEX}.tmp"
trap 'rm -f "$TEMP_FILE"' EXIT

# Ensure workspace directory exists before writing
mkdir -p "${MEMORY_INDEX%/*}"

{
  echo "# Claude Code Memory Context — $TIMESTAMP"
  echo ""
  echo "Generated by sync-claude-memory.sh. Do not edit manually."
  echo ""
} > "$TEMP_FILE"

count=0
skipped=0
while IFS= read -r mem_file; do
    # Explicit existence/readability check — report skip instead of silent failure
    if [[ ! -r "$mem_file" ]]; then
        echo "claude-memory: skipped (unreadable): $mem_file" >&2
        skipped=$((skipped + 1))
        continue
    fi

    # project_dir = memory/ subdirectory; go one level up to get the project name
    project_dir=$(dirname "$mem_file")
    project_name=$(basename "$(dirname "$project_dir")")

    echo "## [$project_name]"
    echo ""
    # Include non-empty, non-header lines from the memory file
    grep -v '^# Memory Index$' "$mem_file" | grep -v "^$" || true
    echo ""
    count=$((count + 1))
done < <(find "$CLAUDE_PROJECTS_DIR" -mindepth 2 -maxdepth 3 -name "MEMORY.md" 2>/dev/null | sort) >> "$TEMP_FILE"

{
  echo "---"
  echo ""
  echo "*Synced $count memory files at $TIMESTAMP*"
} >> "$TEMP_FILE"

# Atomic rename
mv -f "$TEMP_FILE" "$MEMORY_INDEX"
trap - EXIT

echo "claude-memory: synced $count files -> $MEMORY_INDEX"
if [[ $skipped -gt 0 ]]; then
  echo "claude-memory: $skipped files skipped (unreadable)"
fi
