#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

MAP_FILE="${MAP_FILE:-$ROOT_DIR/scripts/smartclaw-export-map.tsv}"
REPORT_FILE="${REPORT_FILE:-$ROOT_DIR/docs/SMARTCLAW_PORTABILITY_AUDIT.md}"

# Files under these prefixes are candidates for portability.
INCLUDE_PREFIXES=(
  ".github/workflows/"
  ".claude/commands/"
  ".claude/skills/"
  "docs/"
  "launchd/"
  "scripts/"
  "skills/"
  "tests/"
)

# Top-level files that are usually useful to other operators.
INCLUDE_FILES=(
  "README.md"
  "install.sh"
  "health-check.sh"
  "monitor-agent.sh"
  "doctor.sh"
  "startup-check.sh"
  "agent-orchestrator.yaml"
  "AUTO_START_GUIDE.md"
  "BACKUP_AND_RESTORE.md"
  "SETUP.md"
  "SLACK_SETUP_GUIDE.md"
)

# Anything matching this regex is treated as non-portable/private/runtime-specific.
EXCLUDE_REGEX='^(\.beads/|\.cursor/|\.smartclaw/|\.pytest_cache/|agents/|artifacts/|browser/|canvas/|credentials/|cron/|delivery-queue/|devices/|identity/|locks/|logs/|media/|memory/|qdrant_storage/|specs/|state/|workspace/memory/|docs/context/|docs/superpowers/|docker/data/|\.smartclaw-audit/|openclaw\.json($|\.)|lcm\.db|lcm\.db-shm|lcm\.db-wal|mem0-history\.db|sessions\.db|.*\.bak(\..*)?$|.*\.sqlite$|.*\.db$)'

# Additional targeted exclusions for internal-only or generated artifacts.
EXCLUDE_PATHS=(
  ".github/workflows/ci-quick.yml"
  "docs/AGENTO_QUICK_REFERENCE.md"
  "docs/superpowers/plans/2026-03-28-sync-to-smartclaw.md"
  "launchd/ai.smartclaw.config-sync.plist.template"
  "scripts/generate_redacted_config.py"
  "scripts/install-config-sync.sh"
  "scripts/sync-openclaw-config.sh"
  "scripts/verify-config-from-redacted.sh"
)

is_included_candidate() {
  local path="$1"
  local prefix
  for prefix in "${INCLUDE_PREFIXES[@]}"; do
    if [[ "$path" == "$prefix"* ]]; then
      return 0
    fi
  done
  local file
  for file in "${INCLUDE_FILES[@]}"; do
    if [[ "$path" == "$file" ]]; then
      return 0
    fi
  done
  return 1
}

is_excluded_path() {
  local path="$1"
  local blocked
  if [[ "$path" =~ $EXCLUDE_REGEX ]]; then
    return 0
  fi
  for blocked in "${EXCLUDE_PATHS[@]}"; do
    if [[ "$path" == "$blocked" ]]; then
      return 0
    fi
  done
  return 1
}

dest_path_for() {
  local src="$1"
  local dst="$src"
  if [[ "$src" == launchd/ai.smartclaw.* ]]; then
    dst="launchd/${src#launchd/ai.smartclaw.}"
    dst="launchd/smartclaw.${dst#launchd/}"
  elif [[ "$src" == launchd/ai.agento-manager.plist.template ]]; then
    dst="launchd/smartclaw.agento-manager.plist.template"
  fi
  printf '%s' "$dst"
}

TMP_MAP="$(mktemp "${TMPDIR:-/tmp}/smartclaw-export-map.XXXXXX")"
TMP_INCLUDED="$(mktemp "${TMPDIR:-/tmp}/smartclaw-export-included.XXXXXX")"
TMP_EXCLUDED="$(mktemp "${TMPDIR:-/tmp}/smartclaw-export-excluded.XXXXXX")"
trap 'rm -f "$TMP_MAP" "$TMP_INCLUDED" "$TMP_EXCLUDED"' EXIT

echo "# Generated by scripts/update-smartclaw-export-map.sh" > "$TMP_MAP"
echo "# Format: <source_path><TAB><destination_path>" >> "$TMP_MAP"

while IFS= read -r path; do
  if ! is_included_candidate "$path"; then
    continue
  fi

  if is_excluded_path "$path"; then
    echo "$path" >> "$TMP_EXCLUDED"
    continue
  fi

  dst="$(dest_path_for "$path")"
  printf '%s\t%s\n' "$path" "$dst" >> "$TMP_MAP"
  echo "$path" >> "$TMP_INCLUDED"
done < <(git ls-files)

# Keep output stable and deterministic.
{
  head -n 2 "$TMP_MAP"
  tail -n +3 "$TMP_MAP" | sort
} > "$MAP_FILE"

INCLUDED_COUNT=$(wc -l < "$TMP_INCLUDED" | tr -d ' ')
EXCLUDED_COUNT=$(wc -l < "$TMP_EXCLUDED" | tr -d ' ')
TOTAL_COUNT=$((INCLUDED_COUNT + EXCLUDED_COUNT))

mkdir -p "$(dirname "$REPORT_FILE")"
{
  echo "# SmartClaw Portability Audit"
  echo
  echo "Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo
  echo "## Summary"
  echo
  echo "- Candidate files evaluated: ${TOTAL_COUNT}"
  echo "- Included in export map: ${INCLUDED_COUNT}"
  echo "- Excluded as non-portable/private/runtime: ${EXCLUDED_COUNT}"
  echo
  echo "## Selection Rules"
  echo
  echo "Portable candidates are selected from:"
  echo "- \`.github/workflows/\`, \`.claude/commands/\`, \`.claude/skills/\`, \`docs/\`, \`launchd/\`, \`scripts/\`, \`skills/\`, \`tests/\`"
  echo "- Plus selected top-level operator files (README/install/health/monitor/doctor/startup/AO config)"
  echo
  echo "Non-portable paths are excluded when they contain:"
  echo "- Secrets, credentials, personal runtime state, local DB/log/cache artifacts"
  echo "- OpenClaw live config files and backups (\`openclaw.json*\`)"
  echo "- Internal-only context snapshots and generated local audit artifacts"
  echo
  echo "## Included Files (sample)"
  echo
  if [[ "$INCLUDED_COUNT" -gt 0 ]]; then
    sed -n '1,60p' "$TMP_INCLUDED" | sed 's/^/- `/' | sed 's/$/`/'
    if [[ "$INCLUDED_COUNT" -gt 60 ]]; then
      echo "- _...truncated; see \`scripts/smartclaw-export-map.tsv\` for full list._"
    fi
  else
    echo "- _(none)_"
  fi
  echo
  echo "## Excluded Files (sample)"
  echo
  if [[ "$EXCLUDED_COUNT" -gt 0 ]]; then
    sed -n '1,40p' "$TMP_EXCLUDED" | sed 's/^/- `/' | sed 's/$/`/'
    if [[ "$EXCLUDED_COUNT" -gt 40 ]]; then
      echo "- _...truncated; private/runtime files remain excluded._"
    fi
  else
    echo "- _(none)_"
  fi
} > "$REPORT_FILE"

echo "Updated map: $MAP_FILE"
echo "Updated report: $REPORT_FILE"
echo "Included: $INCLUDED_COUNT | Excluded: $EXCLUDED_COUNT"
